import {
	chn,
	bra,
	nga,
	usa,
	tur,
	spa,
	ger,
	ser,
	sen,
	egy,
	fra,
	eng,
	ukr,
	uk,
	pak,
	ken,
	jpn,
	irn,
	gha,
	arg,
	can,
	cam,
	aus,
	kor,
	ind,
} from "../assets";
export const pictureList = [
	{
		id: 0,
		tags: ["green", "white", "Africa"],
		image: nga,
		name: "Nigeria",
	},
	{
		id: 1,
		tags: ["stars", "red", "white", "blue", "americas"],
		image: usa,
		name: "United States of America",
	},
	{
		id: 2,
		tags: ["red", "blue", "white", "queen elizabeth", "europe"],
		image: uk,
		name: "United Kingdom",
	},
	{
		id: 3,
		tags: ["green", "yellow", "blue", "neymar", "americas"],
		image: bra,
		name: "Brazil",
	},
	{
		id: 4,
		tags: ["yellow", "blue", "Europe"],
		image: ukr,
		name: "Ukraine",
	},
	{
		id: 5,
		tags: ["white", "red", "asia"],
		image: jpn,
		name: "Japan",
	},
	{
		id: 6,
		tags: ["yellow", "red", "stars", "asia"],
		image: chn,
		name: "China",
	},
	{
		id: 7,
		tags: ["black", "red", "yellow", "europe"],
		image: ger,
		name: "Germany",
	},
	{
		id: 8,
		tags: ["yellow", "red", "crown", "europe"],
		image: spa,
		name: "Spain",
	},
	{
		id: 9,
		tags: ["star", "white", "red", "moon", "europe", "asia"],
		image: tur,
		name: "Turkey",
	},
	{
		id: 10,
		tags: ["asia", "green", "white", "red"],
		image: irn,
		name: "Iran",
	},
	{
		id: 11,
		tags: ["asia", "yellow", "white", "green"],
		image: ind,
		name: "India",
	},
	{
		id: 12,
		tags: ["red", "white", "blue", "crown"],
		image: ser,
		name: "Serbia",
	},
	{
		id: 13,
		tags: ["Africa", "star", "green", "red", "yellow"],
		image: sen,
		name: "Senegal",
	},
	{
		id: 14,
		tags: ["Africa", "eagle", "black", "white", "red"],
		image: egy,
		name: "Egypt",
	},
	{
		id: 15,
		tags: ["red", "green", "yellow", "star", "africa"],
		image: gha,
		name: "Ghana",
	},
	{
		id: 16,
		tags: ["africa", "black", "red", "white", "green"],
		image: ken,
		name: "Kenya",
	},
	{
		id: 17,
		tags: ["moon", "star", "asia"],
		image: pak,
		name: "Pakistan",
	},
	{
		id: 18,
		tags: ["white", "red", "europe"],
		image: eng,
		name: "England",
	},
	{
		id: 19,
		tags: ["red", "white", "blue", "europe"],
		image: fra,
		name: "France",
	},
	{
		id: 20,
		tags: ["white", "red", "blue", "black", "asia"],
		image: kor,
		name: "South Korea",
	},
	{
		id: 21,
		tags: ["star", "white", "red", "blue"],
		image: aus,
		name: "Austrailia",
	},
	{
		id: 22,
		tags: ["star", "Africa", "green", "yellow", "red"],
		image: cam,
		name: "Cameroon",
	},
	{
		id: 23,
		tags: ["white", "red", "flower", "leaf", "americas"],
		image: can,
		name: "Canada",
	},
	{
		id: 24,
		tags: ["blue", "white", "americas"],
		image: arg,
		name: "Argentina",
	},
];
